name: "Go PropGen Action"
description: "Generate build.properties and deploy.properties from vars/secrets"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.3'
    - run: go run ./.github/actions/gh-propgen/main.go
      shell: bash